# Generated by Django 4.2.5 on 2023-09-30 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_profile_bookmark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="author",
            new_name="user",
        ),
    ]
