# Generated by Django 4.2.5 on 2023-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0003_rename_author_photo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_bad_quality",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/bad_quality/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="images/good_quality/%Y/%m/"),
        ),
    ]
