# Generated by Django 4.2.5 on 2023-10-12 20:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_image_bad_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
