# Generated by Django 4.2.5 on 2023-10-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_images/%Y/%m/'),
        ),
    ]
