# Generated by Django 4.2.5 on 2023-10-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_remove_profile_instagram_link_profile_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_bad_quality',
        ),
    ]
